name: Streamlit Deploy

# This specifies when the workflow should run: on push or pull request to the main branch
on:
  push:
    branches:
      - main  # Change this if you're using a different branch
  pull_request:

# The 'jobs' section defines the tasks GitHub Actions will run
jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python on the runner
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # Replace this with the Python version you're using

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Streamlit app (optional if you're deploying directly from Streamlit Cloud)
    - name: Deploy to Streamlit
      run: |
        streamlit run main.py  # Make sure 'main.py' is the correct entry point for your app
